import { useTranslation } from "react-i18next";import { Link } from "react-router-dom";
export function AboutPage(){const {t}=useTranslation();return <div className="about-page">
<section className="about-hero"><p className="section-label">ABOUT / 2026</p><h1>{t("aboutPage.hero")}</h1></section>
<section className="about-story"><div><p className="section-label">01 / STORY</p><h2>{t("aboutPage.storyTitle")}</h2></div><div><p>{t("aboutPage.story1")}</p><p>{t("aboutPage.story2")}</p></div></section>
<section className="field-story dark-page-section"><div className="field-copy"><p className="section-label">02 / FIELD CONTEXT</p><h2>{t("aboutPage.fieldTitle")}</h2><p>{t("aboutPage.fieldCopy")}</p><p className="field-note">{t("aboutPage.fieldNote")}</p></div><figure className="field-photo-slot"><div><span>DOCUMENTARY ASSET</span><strong>MINING / FIELD</strong><small>PHOTO RESERVED FOR ASTRA ART DIRECTION</small></div><figcaption>Personal field photograph · Mining operations · Peru</figcaption></figure></section>
<section className="about-process dark-page-section"><p className="section-label">03 / HOW I WORK</p><h2>PROBLEM → SYSTEM → PRODUCT</h2><div className="process-grid"><article><span>01</span><h3>UNDERSTAND</h3><p>{t("aboutPage.understand")}</p></article><article><span>02</span><h3>DESIGN</h3><p>{t("aboutPage.design")}</p></article><article><span>03</span><h3>BUILD</h3><p>{t("aboutPage.build")}</p></article></div></section>
<section className="focus-section"><p className="section-label">04 / CURRENT FOCUS</p>{["PRODUCT ENGINEERING","SOFTWARE ARCHITECTURE","FULL STACK ENGINEERING","DATA & AI"].map((x,i)=><div className="focus-row" key={x}><h2>{x}</h2><span>0{i+1}</span></div>)}</section>
<section className="tools-section dark-page-section"><p className="section-label">05 / TECHNOLOGIES</p><h2>TOOLS, NOT IDENTITY.</h2><p>TypeScript · React · Node.js · PostgreSQL · Python · SQL · Power BI · Git · Docker</p></section>
<section className="about-next"><h2>{t("aboutPage.cta")}</h2><Link className="text-link underline-link" to="/contact">CONTACT ↗</Link></section>
</div>}